### ISSUE TITLE
Please add max size to decoder.

### ISSUE THREAD

**Issue by marcopeereboom** [davecgh/go-xdr#2]
When reading XDR directly of the wire a remote malicious person could craft packets that could use up all of machines memory because there are no limits.  It would be helpful if we could set a limit on how large a read can be.  For example:

``` golang
dec := NewDecoderLimited(myReader, 1024*1024) // limit to 1MB
_, err := dec.Decode(&myXDR)
if err == xdr.ErrTooBig {
        myReader.Close()
        return err
}
```

**Comment by Merovius** [comment]
You can use [io.LimitReader](http://golang.org/pkg/io/#LimitReader) to do this, which is the idiomatic way.
